version: 2
updates:
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: weekly
    time: "03:00"
    day: friday
  open-pull-requests-limit: 10
  allow:
  - dependency-type: production
